#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTTP-Message
Version  : 6.06
Release  : 19
URL      : http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/HTTP-Message-6.06.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/HTTP-Message-6.06.tar.gz
Summary  : HTTP style messages
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-HTTP-Message-doc
BuildRequires : perl(Encode::Locale)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(IO::HTML)
BuildRequires : perl(LWP::MediaTypes)
BuildRequires : perl(URI)

%description
The HTTP-Message distribution contains classes useful for representing the
messages passed in HTTP style communication.  These are classes representing
requests, responses and the headers contained within them.

%package doc
Summary: doc components for the perl-HTTP-Message package.
Group: Documentation

%description doc
doc components for the perl-HTTP-Message package.


%prep
%setup -q -n HTTP-Message-6.06

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.0/HTTP/Config.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Headers.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Headers/Auth.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Headers/ETag.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Headers/Util.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Message.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Request.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Request/Common.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Response.pm
/usr/lib/perl5/site_perl/5.26.0/HTTP/Status.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
